spring:
  application:
    name: memo

  flyway:
    enabled: true
    baseline-on-migrate: true

  profiles:
    active: @spring.profiles.active@

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.iven.memo.models.DO
  map-underscore-to-camel-case: true