spring:
  application:
    name: memo

  flyway:
    enabled: true
    baseline-on-migrate: true

  profiles:
    active: @spring.profiles.active@

  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.iven.memo.models.DO
  map-underscore-to-camel-case: true

security:
  jwt:
    secret: testSecretKeyForJwtGenerationAndValidation
    expire-day: 7
  allow-request-without-auth:
    post:
      - /users/login
